# Generated by Django 4.2.4 on 2023-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Card Number', 'Card Number'), ('Phone Number', 'Phone Number'), ('Email Address', 'Email Address')], max_length=20)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Numeric', 'Numeric'), ('Boolean', 'Boolean'), ('String', 'String')], max_length=10)),
                ('variable', models.CharField(choices=[('card_number', 'Card Number'), ('ip_address', 'IP Address'), ('email', 'Email'), ('phone', 'Phone'), ('country', 'Country'), ('datetime', 'Datetime'), ('amount', 'Amount'), ('currency', 'Currency'), ('transaction_type', 'Transaction Type')], max_length=20)),
                ('operator', models.CharField(choices=[('GreaterThan', 'Greater Than'), ('SmallerThan', 'Smaller Than'), ('IsEqual', 'Is Equal'), ('IsNotEqual', 'Is Not Equal'), ('Contains', 'Contains')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=12)),
                ('ip_address', models.GenericIPAddressField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('transaction_type', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('fraud_details', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Card Number', 'Card Number'), ('Phone Number', 'Phone Number'), ('Email Address', 'Email Address')], max_length=20)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('actions', models.CharField(choices=[('Blacklist Email', 'Blacklist Email'), ('Blacklist Phone', 'Blacklist Phone'), ('Blacklist Card Number', 'Blacklist Card Number'), ('Reject Transaction', 'Reject Transaction'), ('Blacklist IP Address', 'Blacklist IP Address')], max_length=30)),
                ('condition', models.ManyToManyField(related_name='rules', to='engine.condition')),
            ],
        ),
    ]
