# Generated by Django 4.2.4 on 2023-08-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Blacklist Email', 'Blacklist Email'), ('Blacklist Phone', 'Blacklist Phone'), ('Blacklist Card Number', 'Blacklist Card Number'), ('Reject Transaction', 'Reject Transaction'), ('Blacklist IP Address', 'Blacklist IP Address')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='condition',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='rule',
            name='actions',
        ),
        migrations.AddField(
            model_name='rule',
            name='actions',
            field=models.ManyToManyField(to='engine.action'),
        ),
    ]
